apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.image.readinessProbe.httpGet.path  }}
              port: {{ .Values.image.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.image.livenessProbe.httpGet.path  }}
              port: {{ .Values.image.containerPort }}
          resources:
            requests:
              memory: {{ .Values.image.resources.requests.memory }}
              cpu: {{ .Values.image.resources.requests.cpu }}
            limits:
              memory: {{ .Values.image.resources.limits.memory }}
              cpu:  {{ .Values.image.resources.limits.cpu }}
      imagePullSecrets:
      - name: dockerhub-secret

