apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
        - "values-prod.yaml"
        - "dockerhub-secret.yaml"
    repoURL: https://github.com/theomelo/udacity-nd064-techtrends-project
    path: "helm"
    targetRevision: "HEAD"
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
