apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: melostbr/techtrends
        ports:
        - containerPort: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
      imagePullSecrets:
      - name: dockerhub-secret
