apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
spec:
  selector:
    app: techtrends
  ports:
  - protocol: TCP
    port: 4111
    targetPort: 3111
  type: ClusterIP