apiVersion: v1
kind: Secret
metadata:
  namespace: sandbox
  name: dockerhub-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXVnNiM04wWW5JNk4yRmpZV1ZpT0RjdFlqQmxZUzAwTkRBeUxXRTRaR1V0WW1JM1pqSmhPVFV4WlRZeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson