namespace:
  name: sandbox
deploy:
  replicaCount: 1
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: techtrends
  tag: latest
  containerPort: 3111
  pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m