app:
  name: techtrends
namespace:
  name: sandbox
deploy:
  replicaCount: 1
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  name: techtrends
  repository: melostbr/techtrends:latest
  containerPort: 3111
  pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /healthz
  livenessProbe:
    httpGet:
      path: /healthz
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
